:sparkles: Added WP-CLI

diff --git a/images/4.9/php7.0-apache/Dockerfile b/images/4.9/php7.0-apache/Dockerfile
--- a/images/4.9/php7.0-apache/Dockerfile
+++ b/images/4.9/php7.0-apache/Dockerfile
@@ -2,7 +2,9 @@ FROM wordpress:4.9-php7.0-apache
 
 LABEL maintainer="mb.mathieu.brunot@gmail.com"
 
-RUN apt-get update && \
+RUN set -ex; \
+	\
+    apt-get update && \
     apt-get install --no-install-recommends -y \
 		bzip2 \
 		csstidy \
@@ -18,9 +20,11 @@ RUN apt-get update && \
         libfreetype6-dev \
         libicu-dev \
         libjpeg-dev \
+        libjpeg-turbo-dev \
         libldap2-dev \
         libmcrypt-dev \
         libmemcached-dev \
+        libpng-dev \
         libpng12-dev \
         libpq-dev \
         libxml2-dev \
@@ -66,10 +70,46 @@ RUN apt-get update && \
     curl -o simple-ldap-login.zip -L https://downloads.wordpress.org/plugin/simple-ldap-login.1.6.0.zip && \
         unzip -o simple-ldap-login.zip && \
         chown -R www-data:www-data simple-ldap-login && \
-        rm -f simple-ldap-login.zip && \
-    # Cleanup
-    rm -rf /var/lib/apt/lists/*
+        rm -f simple-ldap-login.zip
 
+
+# pub   2048R/2F6B6B7F 2016-01-07
+#       Key fingerprint = 3B91 9162 5F3B 1F1B F5DD  3B47 673A 0204 2F6B 6B7F
+# uid                  Daniel Bachhuber <daniel@handbuilt.co>
+# sub   2048R/45F9CDE2 2016-01-07
+ENV WORDPRESS_CLI_GPG_KEY 3B9191625F3B1F1BF5DD3B47673A02042F6B6B7F
+
+ENV WORDPRESS_CLI_VERSION 1.5.1
+ENV WORDPRESS_CLI_SHA512 8693cdbc06cca37be9976c4f76aa81c111095f88bb121277cbdfa85f8a2ada3b9133cd9641c439e6f5579d3469a1a44488e872ecbff3d3eba0488bbc8033d6d8
+
+WORKDIR /var/www/html
+
+RUN set -ex; \
+	\
+    # Install wp-cli dependencies
+    #
+    apt-get install --no-install-recommends -y \
+		gnupg \
+		less \
+		mysql-client \
+	; \
+	\
+	curl -o /usr/local/bin/wp.gpg -fSL "https://github.com/wp-cli/wp-cli/releases/download/v${WORDPRESS_CLI_VERSION}/wp-cli-${WORDPRESS_CLI_VERSION}.phar.gpg"; \
+	\
+	export GNUPGHOME="$(mktemp -d)"; \
+	gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$WORDPRESS_CLI_GPG_KEY"; \
+	gpg --batch --decrypt --output /usr/local/bin/wp /usr/local/bin/wp.gpg; \
+	rm -rf "$GNUPGHOME" /usr/local/bin/wp.gpg; \
+	\
+	echo "$WORDPRESS_CLI_SHA512 */usr/local/bin/wp" | sha512sum -c -; \
+	chmod +x /usr/local/bin/wp; \
+	\
+    # Cleanup
+    rm -rf /var/lib/apt/lists/* && \
+	\
+	wp --allow-root --version
+
+USER www-data
 
 # ENTRYPOINT resets CMD
 ENTRYPOINT ["docker-entrypoint.sh"]
